spring.application.name=demo
server.port=4002

# Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?user=postgres.lsolbrclywrcpyggjydo&password=Gkqh8mUh0RWOm2OD&prepareThreshold=0
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=f0SYKiA5wyR5ufg2V6rKSMB1i664Ca3KSvGuu+YU+xHJN1lOPIICZjJB9grc6GVYGM4oMfoWkNSM7H+qoxAS3Q==
jwt.expiration-ms=86400000
